name: CSS Sustentável - uma abordagem para escrever CSS modular, escalável e sustentável | por Adam Silver
markdown: kramdown
url: http://csssustentavel.com.br
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/
description: CSS Sustentável é uma abordagem para escrever CSS modular, escalável e, claro, sustentável.
